### ISSUE TITLE
项目运行不成功，新下载下来，安装以来之后 运行不起来

### ISSUE THREAD

**Issue by lazyTai** [hackycy/sf-midway-admin#16]
> sf-midway-admin@2.0.1 dev D:\code\m1\sf-midway-admin-dev
> cross-env ets && cross-env NODE_ENV=local midway-bin dev --ts

- Midway Starting [ Midway ] 
  TypeError: Cannot read property 'default' of undefined
      at AutoConfiguration.loadQueue (D:\code\m1\sf-midway-admin-dev\node_modules\_midway-bull@0.0.6@midway-bull\dist\configuration.js:34:34)
      at AutoConfiguration.onReady (D:\code\m1\sf-midway-admin-dev\node_modules\_midway-bull@0.0.6@midway-bull\dist\configuration.js:21:20)
      at MidwayWebFramework.loadLifeCycles (D:\code\m1\sf-midway-admin-dev\node_modules\_@midwayjs_core@2.14.6@@midwayjs\core\dist\baseFramework.js:338:38)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at MidwayWebFramework.loadExtension (D:\code\m1\sf-midway-admin-dev\node_modules\_@midwayjs_core@2.14.6@@midwayjs\core\dist\baseFramework.js:176:9)
      at AppBootHook.willReady (D:\code\m1\sf-midway-admin-dev\node_modules\_@midwayjs_web@2.14.7@@midwayjs\web\app.js:34:5)

2022-03-30 17:22:37,974 ERROR 21752 [-/127.0.0.1/-/0ms GET /] TypeError: Cannot read property 'default' of undefined
    at AutoConfiguration.loadQueue (D:\code\m1\sf-midway-admin-dev\node_modules\_midway-bull@0.0.6@midway-bull\dist\configuration.js:34:34)
    at AutoConfiguration.onReady (D:\code\m1\sf-midway-admin-dev\node_modules\_midway-bull@0.0.6@midway-bull\dist\configuration.js:21:20)
    at MidwayWebFramework.loadLifeCycles (D:\code\m1\sf-midway-admin-dev\node_modules\_@midwayjs_core@2.14.6@@midwayjs\core\dist\baseFramework.js:338:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at MidwayWebFramework.loadExtension (D:\code\m1\sf-midway-admin-dev\node_modules\_@midwayjs_core@2.14.6@@midwayjs\core\dist\baseFramework.js:176:9)
    at AppBootHook.willReady (D:\code\m1\sf-midway-admin-dev\node_modules\_@midwayjs_web@2.14.7@@midwayjs\web\app.js:34:5)

TypeError: Cannot read property 'default' of undefined
    at AutoConfiguration.loadQueue (D:\code\m1\sf-midway-admin-dev\node_modules\_midway-bull@0.0.6@midway-bull\dist\configuration.js:34:34)
    at AutoConfiguration.onReady (D:\code\m1\sf-midway-admin-dev\node_modules\_midway-bull@0.0.6@midway-bull\dist\configuration.js:21:20)
    at MidwayWebFramework.loadLifeCycles (D:\code\m1\sf-midway-admin-dev\node_modules\_@midwayjs_core@2.14.6@@midwayjs\core\dist\baseFramework.js:338:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at MidwayWebFramework.loadExtension (D:\code\m1\sf-midway-admin-dev\node_modules\_@midwayjs_core@2.14.6@@midwayjs\core\dist\baseFramework.js:176:9)
    at AppBootHook.willReady (D:\code\m1\sf-midway-admin-dev\node_modules\_@midwayjs_web@2.14.7@@midwayjs\web\app.js:34:5)
[ Midway ] start error: Cannot read property 'default' of undefined

**Comment by hackycy** [comment]
`config.local.ts`配置看一下

**Comment by hackycy** [comment]
或者把`docs`文件夹下的`sample`有一个配置事例拷贝过去然后修改成你的项目配置

**Comment by lazyTai** [comment]
> `config.local.ts`配置看一下

ok  可以成功 ，修改了自己的mysql+redis为自己的账号密码，记得 config.bull  也有个redis的配置，刚才一直没看见 ~~
